services:
  db:
    image: postgres:15
    container_name: url_shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-url_shortener}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@db:5432/${POSTGRES_DB:-url_shortener}
      BASE_URL: http://localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:cached
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
